version: '3.8'

services:
    nodejs:
        image: node:16-slim
        container_name: geoapi
        restart: always
        ports:
            - 60004:60001
        volumes:
            - .:/app
        working_dir: /app
        command: 
            - sh
            - -c
            - |
                npm i
                npm run start
